### ISSUE TITLE
As an internet user I need to login and connect over an encrypted https connection.

### ISSUE THREAD

**Issue by kmclellan** [kmclellan/mstc#81]
All user data needs to be kept confidential when logged in so secure connections need to be used.

Heroku deployments seem to use https by default but the application should force the issue.

**Comment by t01wtb16** [comment]
I've configured the application to force https in production via the config/environments/production.rb with the following:

"config.force_ssl = true".

**Comment by kmclellan** [comment]
Thanks William, that's exactly what I had in mind.  I just couldn't remember how it was done.
